Registration
Velixeor/Thesis-Defense-Management-System pull request #6
Opened 2024-09-29 09:50 UTC by Velixeor

2024-09-29 23:11 UTC, mkskobaro requested changes
Поправить что есть, и учитывать готовящийся коммит, который изменит доменную модель

2024-09-29 23:11 UTC, mkskobaro commented on server/src/main/java/ru/tubryansk/tdms/controller/UserController.java
> +
добвить в httpEndpointConfiguration()

2024-09-29 23:11 UTC, mkskobaro commented on server/src/main/java/ru/tubryansk/tdms/dto/StudentDTO.java
> +@Builder
переписать на record

2024-09-29 23:11 UTC, mkskobaro commented on server/src/main/java/ru/tubryansk/tdms/exception/TDMSException.java
> +public class TDMSException extends RuntimeException{
удалить

2024-09-29 23:11 UTC, mkskobaro commented on server/src/main/java/ru/tubryansk/tdms/exception/user/UserCreationException.java
> +public class UserCreationException extends TDMSException {
Переписать на BusinessException

2024-09-29 23:11 UTC, mkskobaro commented on server/src/main/java/ru/tubryansk/tdms/exception/user/UserUpdateException.java
> +public class UserUpdateException extends TDMSException {
Переписать на BusinessException

2024-09-29 23:11 UTC, mkskobaro commented on server/src/main/java/ru/tubryansk/tdms/repository/RoleRepository.java
> +    Role getRoleById(Integer id);
убрать, т.к. JpaRepository предоставляет findRoleById()

2024-09-29 23:11 UTC, mkskobaro commented on server/src/main/java/ru/tubryansk/tdms/repository/UserRepository.java
> +  List<User> getAll();
Убрать -//-

2024-09-29 23:11 UTC, mkskobaro commented on server/src/main/java/ru/tubryansk/tdms/repository/UserRepository.java
> +  Boolean existsUserByLoginAndAndMailAndNumberPhone(String login, String numberPhone, String mail);
переименовать 
existsUserByLoginAndAndMailAndNumberPhone -> existsUserByLoginAndOrMailOrNumberPhone

2024-09-29 23:11 UTC, mkskobaro commented on server/src/main/java/ru/tubryansk/tdms/service/UserService.java
> +    private void transferringDataInUserFromUserDTO(final UserDTO userDTO, User user) {
убрать и перенести в DTO

2024-09-29 23:11 UTC, mkskobaro commented on server/src/main/java/ru/tubryansk/tdms/service/UserService.java
> +    private UserDTO transferringDataInUserDTOFromUser(final User user) {
-//-

2024-09-29 23:11 UTC, mkskobaro commented on server/src/main/java/ru/tubryansk/tdms/controller/UserController.java
> +
Лишняя строка

2024-09-29 23:11 UTC, mkskobaro commented on server/src/main/java/ru/tubryansk/tdms/controller/UserController.java
> +    @GetMapping("/get-all")
Отступ между методами

2024-09-29 23:11 UTC, mkskobaro commented on server/src/main/java/ru/tubryansk/tdms/repository/UserRepository.java
> +  @Query("SELECT COUNT(u) > 0 FROM User u WHERE u.login = :login OR u.mail = :mail OR u.numberPhone = :numberPhone")
spring data jpa умеет его сам генерировать, убрать

2024-09-29 23:11 UTC, mkskobaro commented on server/src/main/java/ru/tubryansk/tdms/repository/UserRepository.java
> +  List<User> findByLoginOrMailOrNumberPhone(String login, String mail, String numberPhone);
отступ 1 строка между методами

2024-09-29 23:11 UTC, mkskobaro commented on server/src/main/java/ru/tubryansk/tdms/service/UserService.java
> +    }
отступ 1 строка между методами

2024-09-29 23:11 UTC, mkskobaro commented on web/src/components/MainPage.tsx
> +interface HeaderProps {
отступ от импортов

2024-09-29 23:11 UTC, mkskobaro commented on web/src/components/auth/registration/RegistrationForm.tsx
> +                            <Form.Label>Полное имя</Form.Label>
ФИО, не имя

2024-09-29 23:11 UTC, mkskobaro commented on web/src/components/auth/registration/RegistrationForm.tsx
> +                        {/* Галочки для выбора ролей */}
может чекбоксы? и дополнительно появиься галочка, если не студент

2024-09-29 23:11 UTC, mkskobaro commented on web/src/components/auth/registration/RegistrationForm.tsx
> +        const userDTO = {
вынести в interface

2024-09-29 23:11 UTC, mkskobaro commented on web/src/components/auth/registration/RegistrationForm.tsx
> +        if (isManager) roleId.push(1); // Руководитель
не нужно использовать id, лучше передать как строку (например ROLE_USER)

2024-09-29 23:11 UTC, mkskobaro commented on server/src/main/java/ru/tubryansk/tdms/controller/UserController.java
> +    @GetMapping("")
не нужно указывать ("") для пустого значения

2024-10-13 14:29 UTC, Velixeor commented on server/src/main/java/ru/tubryansk/tdms/controller/UserController.java
> +
+

2024-10-13 14:29 UTC, Velixeor commented on server/src/main/java/ru/tubryansk/tdms/dto/StudentDTO.java
> +@Builder
+

2024-10-13 14:29 UTC, Velixeor commented on server/src/main/java/ru/tubryansk/tdms/dto/StudentDTO.java
> +@Builder
Сделал

2024-10-13 14:30 UTC, Velixeor commented on server/src/main/java/ru/tubryansk/tdms/exception/TDMSException.java
> +public class TDMSException extends RuntimeException{
Сделал

2024-10-13 14:30 UTC, Velixeor commented on server/src/main/java/ru/tubryansk/tdms/exception/user/UserCreationException.java
> +public class UserCreationException extends TDMSException {
Сделал

2024-10-13 14:30 UTC, Velixeor commented on server/src/main/java/ru/tubryansk/tdms/exception/user/UserUpdateException.java
> +public class UserUpdateException extends TDMSException {
Сделал

2024-10-13 14:30 UTC, Velixeor commented on web/src/components/auth/registration/RegistrationForm.tsx
> +                            <Form.Label>Полное имя</Form.Label>
Сделал

2024-10-13 14:30 UTC, Velixeor commented on server/src/main/java/ru/tubryansk/tdms/controller/UserController.java
> +    @GetMapping("")
Сделал

2024-10-14 05:47 UTC, mkskobaro commented
Нужно будет делать новый ПР, т.к. случился переезд на более свежий мастер

2024-10-14 05:47 UTC, closed without merging